/**
 * Stable, machine-readable error codes shared across backend, admin and mobile.
 * New codes are additive; never repurpose an existing code for a different meaning.
 */
export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // Auth-specific — distinct codes so clients can react differently
  // (e.g. silently refresh on TOKEN_EXPIRED, force full logout on
  // SESSION_REVOKED, show a "contact support" state on ACCOUNT_SUSPENDED).
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  // Birth profile / location / astrology-specific — distinct codes so the
  // mobile app can show a targeted message instead of a generic error.
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  LOCATION_PROVIDER_UNAVAILABLE: 'LOCATION_PROVIDER_UNAVAILABLE',
  FUTURE_DATE_OF_BIRTH: 'FUTURE_DATE_OF_BIRTH',
  ASTROLOGY_ENGINE_UNAVAILABLE: 'ASTROLOGY_ENGINE_UNAVAILABLE',
  // AI Gateway
  AI_GATEWAY_UNAVAILABLE: 'AI_GATEWAY_UNAVAILABLE',
  AI_INVALID_REQUEST: 'AI_INVALID_REQUEST',
  // Wallet & Pricing
  INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
  INVALID_TRANSACTION_AMOUNT: 'INVALID_TRANSACTION_AMOUNT',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  DUPLICATE_IDEMPOTENCY_KEY: 'DUPLICATE_IDEMPOTENCY_KEY',
  WALLET_HOLD_NOT_FOUND: 'WALLET_HOLD_NOT_FOUND',
  WALLET_HOLD_EXPIRED: 'WALLET_HOLD_EXPIRED',
  PRICING_CONFIG_NOT_FOUND: 'PRICING_CONFIG_NOT_FOUND',
  PRICING_INVALID_EFFECTIVE_DATES: 'PRICING_INVALID_EFFECTIVE_DATES',
  // Payments
  PAYMENT_ORDER_NOT_FOUND: 'PAYMENT_ORDER_NOT_FOUND',
  PAYMENT_ORDER_ALREADY_PAID: 'PAYMENT_ORDER_ALREADY_PAID',
  PAYMENT_ORDER_EXPIRED: 'PAYMENT_ORDER_EXPIRED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  INVALID_REFUND_AMOUNT: 'INVALID_REFUND_AMOUNT',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  // Voice
  VOICE_SESSION_NOT_FOUND: 'VOICE_SESSION_NOT_FOUND',
  VOICE_SESSION_ALREADY_ENDED: 'VOICE_SESSION_ALREADY_ENDED',
  VOICE_SESSION_EXPIRED: 'VOICE_SESSION_EXPIRED',
  VOICE_INSUFFICIENT_BALANCE: 'VOICE_INSUFFICIENT_BALANCE',
  VOICE_STT_FAILED: 'VOICE_STT_FAILED',
  VOICE_TTS_FAILED: 'VOICE_TTS_FAILED',
  VOICE_PROVIDER_UNAVAILABLE: 'VOICE_PROVIDER_UNAVAILABLE',
  // Reports
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_ALREADY_COMPLETED: 'REPORT_ALREADY_COMPLETED',
  REPORT_INSUFFICIENT_CREDITS: 'REPORT_INSUFFICIENT_CREDITS',
  REPORT_PARTNER_PROFILE_REQUIRED: 'REPORT_PARTNER_PROFILE_REQUIRED',
  REPORT_JOB_FAILED: 'REPORT_JOB_FAILED',
  REPORT_SCORE_VALIDATION_FAILED: 'REPORT_SCORE_VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
