import {
  NotificationCategory,
  NotificationChannel,
  NotificationEventType,
  type CreateNotificationTemplateInput,
} from '@astroai/shared-types';

export const DEFAULT_NOTIFICATION_TEMPLATES: CreateNotificationTemplateInput[] = [
  {
    templateCode: 'WELCOME_USER',
    name: 'Welcome New User',
    description: 'Sent upon user signup',
    eventType: NotificationEventType.USER_REGISTRATION,
    category: NotificationCategory.LIFECYCLE,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['name'],
    locales: {
      en: {
        title: 'Welcome to AstroAI, {{name}}!',
        body: 'Your celestial journey begins now. Tap to calculate your Vedic birth chart.',
        actionUrl: '/birth-profiles/new',
        actionText: 'Get Started',
      },
      hi: {
        title: 'AstroAI में आपका स्वागत है, {{name}}',
        body: 'अपनी वैदिक जन्म कुंडली बनाने के लिए टैप करें।',
        actionUrl: '/birth-profiles/new',
        actionText: 'शुरू करें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'BIRTH_PROFILE_COMPLETE',
    name: 'Birth Profile Completed',
    description: 'Sent when user saves a birth profile',
    eventType: NotificationEventType.BIRTH_PROFILE_COMPLETION,
    category: NotificationCategory.LIFECYCLE,
    channels: [NotificationChannel.PUSH],
    variables: ['name'],
    locales: {
      en: {
        title: 'Kundli Ready: {{name}}',
        body: 'Your Vedic birth chart has been calculated. Explore your planetary yogas & houses.',
        actionUrl: '/reports/catalog',
        actionText: 'Explore Kundli',
      },
      hi: {
        title: 'जन्म कुंडली तैयार: {{name}}',
        body: 'आपकी जन्म कुंडली तैयार है। अपने योग और ग्रह स्थिति देखें।',
        actionUrl: '/reports/catalog',
        actionText: 'कुंडली देखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'FIRST_CHAT_FOLLOWUP',
    name: 'First Chat Followup',
    description: 'Sent after first AI astrologer conversation',
    eventType: NotificationEventType.FIRST_CHAT,
    category: NotificationCategory.CONSULTATION,
    channels: [NotificationChannel.PUSH],
    variables: ['title'],
    locales: {
      en: {
        title: 'Acharya Vashishta is here for you',
        body: 'Do you have more questions regarding relationships, career, or remedies? Consult anytime.',
        actionUrl: '/chat',
        actionText: 'Continue Consultation',
      },
      hi: {
        title: 'आचार्य वशिष्ठ आपके मार्गदर्शन के लिए उपस्थित हैं',
        body: 'क्या आपके पास करियर या प्रेम से जुड़े और सवाल हैं? परामर्श जारी रखें।',
        actionUrl: '/chat',
        actionText: 'बातचीत जारी रखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'LOW_WALLET_BALANCE_ALERT',
    name: 'Low Balance Alert',
    description: 'Sent when wallet available balance falls below minimum threshold',
    eventType: NotificationEventType.LOW_WALLET_BALANCE,
    category: NotificationCategory.TRANSACTIONAL,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['availableBalance'],
    locales: {
      en: {
        title: 'Low Credits Alert',
        body: 'You have {{availableBalance}} credits remaining. Recharge your wallet to keep consultations uninterrupted.',
        actionUrl: '/wallet',
        actionText: 'Add Credits',
      },
      hi: {
        title: 'कम क्रेडिट अलर्ट',
        body: 'आपके पास केवल {{availableBalance}} क्रेडिट बचे हैं। रिचार्ज करें।',
        actionUrl: '/wallet',
        actionText: 'रिचार्ज करें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'REPORT_GENERATED',
    name: 'Astrology Report Ready',
    description: 'Sent when an asynchronous report finishes PDF generation',
    eventType: NotificationEventType.REPORT_READY,
    category: NotificationCategory.TRANSACTIONAL,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['reportTitle', 'reportId'],
    locales: {
      en: {
        title: 'Your {{reportTitle}} is Ready!',
        body: 'Your comprehensive Vedic report is ready for viewing and PDF download.',
        actionUrl: '/reports/{{reportId}}',
        actionText: 'View Report',
      },
      hi: {
        title: 'आपकी {{reportTitle}} तैयार है',
        body: 'आपकी विस्तृत रिपोर्ट तैयार है। PDF डाउनलोड करें।',
        actionUrl: '/reports/{{reportId}}',
        actionText: 'रिपोर्ट देखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'DAILY_HOROSCOPE_ALERT',
    name: 'Daily Horoscope Ready',
    description: 'Daily morning planetary transit horoscope',
    eventType: NotificationEventType.HOROSCOPE_READY,
    category: NotificationCategory.HOROSCOPE,
    channels: [NotificationChannel.PUSH],
    variables: ['rashi', 'summary'],
    locales: {
      en: {
        title: 'Daily Horoscope for {{rashi}}',
        body: '{{summary}}',
        actionUrl: '/horoscope',
        actionText: 'Read Forecast',
      },
      hi: {
        title: '{{rashi}} के लिए दैनिक राशिफल',
        body: '{{summary}}',
        actionUrl: '/horoscope',
        actionText: 'राशिफल पढ़ें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'PAYMENT_RECEIPT',
    name: 'Payment & Credits Topup Receipt',
    description: 'Sent upon successful payment verification',
    eventType: NotificationEventType.PURCHASE,
    category: NotificationCategory.TRANSACTIONAL,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['credits', 'amount', 'currency', 'orderId'],
    locales: {
      en: {
        title: 'Payment Successful',
        body: 'Added {{credits}} credits to your wallet for {{currency}} {{amount}} (Order: {{orderId}}).',
        actionUrl: '/wallet',
        actionText: 'View Wallet',
      },
      hi: {
        title: 'भुगतान सफल',
        body: 'आपके वॉलेट में {{credits}} क्रेडिट जोड़े गए हैं (ऑर्डर: {{orderId}})।',
        actionUrl: '/wallet',
        actionText: 'वॉलेट देखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'INACTIVITY_NUDGE',
    name: 'Inactivity Re-engagement Nudge',
    description: 'Sent when user is inactive for more than 7 days',
    eventType: NotificationEventType.INACTIVITY,
    category: NotificationCategory.MARKETING,
    channels: [NotificationChannel.PUSH],
    variables: ['name'],
    locales: {
      en: {
        title: 'Planetary Transits are Shifting',
        body: 'Major planetary transits are active in your natal chart. Tap to see this week\'s guidance.',
        actionUrl: '/home',
        actionText: 'Open App',
      },
      hi: {
        title: 'ग्रहों की चाल बदल रही है',
        body: 'आपके चार्ट में नए गोचर सक्रिय हैं। इस सप्ताह का मार्गदर्शन देखें।',
        actionUrl: '/home',
        actionText: 'ऐप खोलें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'BIRTHDAY_GREETING',
    name: 'Annual Solar Return Birthday Blessing',
    description: 'Sent on user birth date',
    eventType: NotificationEventType.BIRTHDAY,
    category: NotificationCategory.LIFECYCLE,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['name'],
    locales: {
      en: {
        title: 'Happy Birthday, {{name}}',
        body: 'May the planetary alignments bring you health, prosperity, and joy on your Solar Return.',
        actionUrl: '/reports/catalog',
        actionText: 'Claim Birthday Offer',
      },
      hi: {
        title: 'जन्मदिन की हार्दिक शुभकामनाएं, {{name}}',
        body: 'ईश्वर और सभी ग्रह आपको उत्तम स्वास्थ्य, समृद्धि और आनंद प्रदान करें।',
        actionUrl: '/reports/catalog',
        actionText: 'जन्मदिन ऑफर देखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'PROMOTIONAL_OFFER',
    name: 'Promotional Campaign Template',
    description: 'Used for broadcast or targeted marketing campaigns',
    eventType: NotificationEventType.PROMOTIONAL_CAMPAIGN,
    category: NotificationCategory.MARKETING,
    channels: [NotificationChannel.PUSH, NotificationChannel.EMAIL],
    variables: ['offerTitle', 'offerBody', 'discount'],
    locales: {
      en: {
        title: '{{offerTitle}}',
        body: '{{offerBody}}',
        actionUrl: '/wallet',
        actionText: 'View Offer',
      },
      hi: {
        title: '{{offerTitle}}',
        body: '{{offerBody}}',
        actionUrl: '/wallet',
        actionText: 'ऑफर देखें',
      },
    },
    isActive: true,
  },
  {
    templateCode: 'REFERRAL_CREDITS_EARNED',
    name: 'Referral Bonus Reward',
    description: 'Sent when a referred friend joins and credits are awarded',
    eventType: NotificationEventType.REFERRAL_REWARD,
    category: NotificationCategory.LIFECYCLE,
    channels: [NotificationChannel.PUSH],
    variables: ['creditsAwarded'],
    locales: {
      en: {
        title: 'Referral Bonus Earned',
        body: 'You received {{creditsAwarded}} bonus credits. Thank you for sharing AstroAI.',
        actionUrl: '/wallet',
        actionText: 'Check Balance',
      },
      hi: {
        title: 'रेफरल बोनस प्राप्त हुआ',
        body: 'आपको {{creditsAwarded}} बोनस क्रेडिट मिले हैं। AstroAI साझा करने के लिए धन्यवाद।',
        actionUrl: '/wallet',
        actionText: 'बैलेंस देखें',
      },
    },
    isActive: true,
  },
];
