import {
  PujaCategory,
  PujaTier,
  type PujaItemDTO,
} from '@astroai/shared-types';

export const SACRED_PUJA_CATALOG: PujaItemDTO[] = [
  {
    id: 'puja-mahamrityunjaya',
    title: 'Maha Mrityunjaya Anushthan & Rudrabhishek',
    sanskritTitle: 'महामृत्युंजय अनुष्ठान एवं रुद्राभिषेक',
    category: PujaCategory.HEALTH_MAHAMRITYUNJAYA,
    deity: 'Lord Shiva (Mahakal)',
    templeName: 'Shri Mahakaleshwar Jyotirlinga',
    templeLocation: 'Ujjain, Madhya Pradesh',
    description:
      'Consecrated 108-Ahuti Rudrabhishek and 11,000 Mahamrityunjaya Japa for longevity, healing severe ailments, mental resilience, and shielding against malefic planetary transits (Maraka dashas & Saturn Sade Sati).',
    vedicSignificance:
      'Rigveda Mandala 7 (Sukta 59.12) - The supreme victory over physical suffering, accidental trauma, and negative psychic karma.',
    benefits: [
      'Relief from acute & chronic physical afflictions',
      'Shields the subtle body during Maraka Graha periods',
      'Infuses radiant Prana and vital life energy (Ayu Vardhana)',
      'Dispels deep karmic fear, anxiety, and grief',
    ],
    auspiciousUpcomingTithi: 'Every Shukla / Krishna Paksha Trayodashi (Pradosham) & Somwar',
    imageUrl: 'https://images.unsplash.com/photo-1609342122563-a43ac8917a3a?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Single Seeker Vedic Sankalpa',
        priceINR: 1100,
        creditsRequired: 22,
        panditCount: 2,
        durationMinutes: 45,
        samagriInclusions: ['Bilva Patra', 'Bhasma', 'Panchamrit', 'Gangajal', 'Rudraksha Mala'],
      },
      {
        tier: PujaTier.SHODASHA_UPCHARA,
        title: 'Sampoorna Kula (Family) Shodashopachara',
        priceINR: 3100,
        creditsRequired: 62,
        panditCount: 5,
        durationMinutes: 90,
        samagriInclusions: [
          'Bilva Patra Archana',
          'Kashi Chandan',
          'Siddha Mahamrityunjaya Yantra',
          'Panchamrit Abhishek',
          'Silver Bilva Leaf',
        ],
      },
      {
        tier: PujaTier.MAHA_ANUSHTHAN,
        title: 'Akhanda 11-Pandit Maha Anushthan',
        priceINR: 11000,
        creditsRequired: 220,
        panditCount: 11,
        durationMinutes: 180,
        samagriInclusions: [
          'Live Sanctum Havan',
          'Gold-Polished Trishul Yantra',
          'Energized 5-Mukhi Rudraksha Mala',
          'Consecrated Mahakal Bhasma',
          'Sacred Dry Fruit & Sweet Prasad Pack',
        ],
      },
    ],
  },
  {
    id: 'puja-navagraha-shanti',
    title: 'Sampoorna Navagraha Maha Shanti Havan',
    sanskritTitle: 'सम्पूर्ण नवग्रह महा शांति हवन',
    category: PujaCategory.GRAHA_SHANTI,
    deity: 'Navagraha Mandala (Surya, Chandra, Mangal, Budha, Guru, Shukra, Shani, Rahu, Ketu)',
    templeName: 'Kashi Vishwanath Corridor Navagraha Temple',
    templeLocation: 'Varanasi (Kashi), Uttar Pradesh',
    description:
      'Harmonizes all 9 celestial grahas in your Janma Kundli. Neutralizes malefic aspects, activates weak benefic planets, and removes hurdles blocking career, health, and family prosperity.',
    vedicSignificance:
      'Brihat Parashara Hora Shastra - Pacifies planetary afflictions across all 12 bhavas and balances the energetic tri-gunas.',
    benefits: [
      'Pacifies agitated planetary dashas & combust grahas',
      'Enhances prosperity, luck, and spiritual growth',
      'Removes unseen obstructions in examinations, job, and court matters',
      'Promotes peace in domestic environment',
    ],
    auspiciousUpcomingTithi: 'Upcoming Amavasya & Purnima Mahapuja',
    imageUrl: 'https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Individual Graha Samidha Havan',
        priceINR: 1500,
        creditsRequired: 30,
        panditCount: 3,
        durationMinutes: 60,
        samagriInclusions: ['9 Sacred Samidha Woods', 'Navadhanya Grains', 'Navagraha Yantra Cloth'],
      },
      {
        tier: PujaTier.SHODASHA_UPCHARA,
        title: 'Family Navagraha Archana & Havan',
        priceINR: 4100,
        creditsRequired: 82,
        panditCount: 7,
        durationMinutes: 120,
        samagriInclusions: [
          '9-Gemstone Navagraha Yantra',
          'Ganga Jal Bottle from Kashi',
          'Navagraha Dhoop & Bhasma',
          'Pure Cow Ghee Havan Ahuti Pack',
        ],
      },
    ],
  },
  {
    id: 'puja-kaalsarp-rahu-ketu',
    title: 'Kaal Sarp & Rahu-Ketu Sarpa Dosha Nivaran',
    sanskritTitle: 'कालसर्प एवं राहु-केतु सर्प दोष निवारण',
    category: PujaCategory.DOSHA_NIVARAN,
    deity: 'Nag Devata & Lord Trimbakeshwar',
    templeName: 'Shri Trimbakeshwar Jyotirlinga',
    templeLocation: 'Nashik, Maharashtra',
    description:
      'Sacred Narayan Nagbali & Sarpa Shanti Vidhi to dissolve karmic knots caused by planets hemmed between Rahu and Ketu in the birth chart. Eliminates recurring financial hurdles, nightmares, and chronic delays.',
    vedicSignificance:
      'Garuda Purana & Muhurta Chintamani - The premier authoritative ritual for Kaal Sarp and Sarpa Dosha clearance.',
    benefits: [
      'Neutralizes complete & partial Kaal Sarp Dosha',
      'Unlocks stalled business, promotions, and wealth flow',
      'Frees lineage from Pitra/Sarpa curses and unrest',
      'Brings deep restful sleep and clarity of purpose',
    ],
    auspiciousUpcomingTithi: 'Nag Panchami & Somvati Amavasya Special',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Silver Nag-Nagin Ahuti Puja',
        priceINR: 2100,
        creditsRequired: 42,
        panditCount: 3,
        durationMinutes: 75,
        samagriInclusions: ['Silver Nag-Nagin Pair', 'Kush Grass', 'Black Sesame', 'Godavari Sacred Water'],
      },
      {
        tier: PujaTier.MAHA_ANUSHTHAN,
        title: 'Sampoorna Trimbakeshwar Nagbali Vidhi',
        priceINR: 7500,
        creditsRequired: 150,
        panditCount: 5,
        durationMinutes: 150,
        samagriInclusions: [
          'Copper Sarpa Yantra (Energized)',
          'Trimbakeshwar Sanctum Vibhuti',
          'Silver Nag Pratima Consecration',
          'Deluxe Dry Fruit & Peda Prasad',
        ],
      },
    ],
  },
  {
    id: 'puja-mangalnath-bhatpuja',
    title: 'Mangal Dosha Shanti Bhat Puja',
    sanskritTitle: 'मंगल दोष शांति भात पूजा',
    category: PujaCategory.RELATIONSHIPS,
    deity: 'Lord Mangalnath (Birthplace of Mars)',
    templeName: 'Shri Mangalnath Mandir',
    templeLocation: 'Ujjain, Madhya Pradesh',
    description:
      'Traditional Cooked-Rice (Bhat) ritual at the primordial epicenter of Mars on Earth. Cools the fiery temperament of Angarak Mangal, resolving marriage delays, spousal conflicts, and blood/vitality imbalances.',
    vedicSignificance:
      'Skanda Purana (Avanti Khanda) - Mangalnath is revered as the celestial birthplace of planet Mars.',
    benefits: [
      'Softens aggressive Manglik Dosha in 1st, 4th, 7th, 8th, 12th houses',
      'Removes obstacles in finding suitable life partner',
      'Prevents divorce, severe marital friction, and domestic disputes',
      'Boosts property, real estate, and sibling harmony',
    ],
    auspiciousUpcomingTithi: 'Every Bhaumwar (Tuesday) & Angaraki Chaturthi',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Siddha Bhat Puja & Kumkum Archana',
        priceINR: 1800,
        creditsRequired: 36,
        panditCount: 2,
        durationMinutes: 60,
        samagriInclusions: ['Sacred Bhat Offering', 'Red Coral Mala Touch', 'Kumkum Sindoor', 'Red Cloth'],
      },
      {
        tier: PujaTier.SHODASHA_UPCHARA,
        title: 'Sampoorna Mangal Nivaran & Vivah Prasiddhi',
        priceINR: 4800,
        creditsRequired: 96,
        panditCount: 5,
        durationMinutes: 120,
        samagriInclusions: [
          'Energized Mangal Yantra (Copper)',
          'Mangalnath Red Kumkum & Dhaga',
          'Saffron Sweets & Dry Fruit Prasad Box',
          'Personalized Gotra Sankalpa Recording',
        ],
      },
    ],
  },
  {
    id: 'puja-lakshmi-kubera-kanakadhara',
    title: 'Maha Lakshmi Kubera & Kanakadhara Stotram Yajna',
    sanskritTitle: 'महालक्ष्मी कुबेर एवं कनकधारा महायज्ञ',
    category: PujaCategory.WEALTH_LAKSHMI,
    deity: 'Goddess Mahalakshmi & Lord Kubera',
    templeName: 'Shri Kolhapur Mahalakshmi Ambabai Temple',
    templeLocation: 'Kolhapur, Maharashtra',
    description:
      '1,008 Lotus Flower Archana and Kanakadhara Yajna for attracting unstinting abundance, dissolving debt traps, unlocking locked assets, and activating the Dhana & Labha Bhavas (2nd & 11th houses).',
    vedicSignificance:
      'Sri Suktam & Adi Shankaracharya Kanakadhara Stotra - The definitive pathway for lasting Sri (spiritual & material wealth).',
    benefits: [
      'Unlocks stagnant cash flow and business profitability',
      'Dissolves heavy loans, debts, and financial volatility',
      'Attracts high-value career offers and lucrative investments',
      'Brings auspicious golden radiance into the household',
    ],
    auspiciousUpcomingTithi: 'Shukravar (Friday) & Dhanteras / Diwali Purnima',
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Kamal Gatta & Sri Suktam Ahuti',
        priceINR: 2100,
        creditsRequired: 42,
        panditCount: 3,
        durationMinutes: 60,
        samagriInclusions: ['108 Lotus Seeds', 'Ashtagandha Chandan', 'Kashi Attar', 'Sri Yantra Coin'],
      },
      {
        tier: PujaTier.MAHA_ANUSHTHAN,
        title: 'Maha Kanakadhara 1008 Lotus Yajna',
        priceINR: 8500,
        creditsRequired: 170,
        panditCount: 7,
        durationMinutes: 150,
        samagriInclusions: [
          'Gold-Polished Meru Sri Yantra',
          'Siddha Lakshmi Kauri & Gomti Chakra Set',
          'Kolhapur Ambabai Consecrated Chunari',
          'Royal Dry Fruit Sweets & Cardamom Prasad Box',
        ],
      },
    ],
  },
  {
    id: 'puja-baglamukhi-shatru-nashak',
    title: 'Maa Baglamukhi Pitambara Shatru Vinashak Anushthan',
    sanskritTitle: 'माँ बगलामुखी पीताम्बरा शत्रु विनाशक अनुष्ठान',
    category: PujaCategory.CAREER_VICTORY,
    deity: 'Maa Baglamukhi (8th Mahavidya)',
    templeName: 'Maa Baglamukhi Shaktipeeth',
    templeLocation: 'Nalkheda, Madhya Pradesh',
    description:
      'Stambhana Shakti Tantric Anushthan with yellow oleander flowers and turmeric roots for overcoming vicious court litigation, corporate sabotage, political rivals, and envious adversaries.',
    vedicSignificance:
      'Tantra Sara & Rudrayamala - Invokes the supreme power to paralyze hostility, falsehood, and malicious speech.',
    benefits: [
      'Decisive breakthrough in contested court cases and legal battles',
      'Neutralizes hidden workplace sabotage and hostile competitors',
      'Shields reputation, honors, and business credibility',
      'Silences false accusations and malicious rumors',
    ],
    auspiciousUpcomingTithi: 'Chaturdashi, Ashtami & Gupt Navratri Nights',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    isLiveStreamAvailable: true,
    isPrasadDeliveryAvailable: true,
    tiers: [
      {
        tier: PujaTier.STANDARD,
        title: 'Pitambara Hridaya Japa & Havan',
        priceINR: 2500,
        creditsRequired: 50,
        panditCount: 3,
        durationMinutes: 75,
        samagriInclusions: ['Yellow Haldi Mala', 'Mustard Seed Ahuti', 'Yellow Cloth', 'Baglamukhi Gutika'],
      },
      {
        tier: PujaTier.MAHA_ANUSHTHAN,
        title: 'Akhanda 36,000 Shatru Vinashak Mahayajna',
        priceINR: 12500,
        creditsRequired: 250,
        panditCount: 11,
        durationMinutes: 180,
        samagriInclusions: [
          'Pure Brass Baglamukhi Yantra',
          'Sanctified Pitambara Raksha Sutra',
          'Nalkheda Havan Bhasma',
          'Energized Turmeric Mala',
          'Exclusive Royal Prasad Package',
        ],
      },
    ],
  },
];
